# Sample data. Lines with leading # signs are comments.
# Change the data below.
- name: PE_REQUIREMENT
  applies_to: []
  exempt:
    - student1@mydiscoveryk8.org
    - student2@mydiscoveryk8.org
  class_or_group_options:
    -  # OR
      - PE_Mon_or_Tue  # AND
      - PE_Thu_or_Fri
    -  # OR
      - PE_2_day_equivalent
    -  # OR
      - PE_Mon_or_Tue  # AND
      - PE_1_day_equivalent
    -  # OR
      - PE_1_day_equivalent  # AND
      - PE_Thu_or_Fri
    -  # OR
      - PE_1_day_equivalent  # AND
      - PE_1_day_equivalent